openapi: 3.1.3
info:
  title: Optic Bookstore Demo Spec
  description: A demo specification for Optic
  contact:
    email: support@useoptic.com
  version: 1.0.0
servers:
  - url: https://bookstore.optic.dev
paths: {}